In [122]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [123]:
df = pd.read_csv('carprices.csv')
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [124]:
le = LabelEncoder()
dfle = df.copy()
dfle['Car Model'] = le.fit_transform(dfle['Car Model'])
dfle

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [125]:
ohe = OneHotEncoder()
dfhe = ohe.fit_transform(df[['Car Model']]).toarray()
dfhe

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [126]:
dfhe = pd.DataFrame(dfhe, columns=ohe.get_feature_names_out(['Car Model']))
dfhe

    Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class
0                 0.0               1.0                              0.0
1                 0.0               1.0                              0.0
2                 0.0               1.0                              0.0
3                 0.0               1.0                              0.0
4                 0.0               1.0                              0.0
5                 1.0               0.0                              0.0
6                 1.0               0.0                              0.0
7                 1.0               0.0                              0.0
8                 1.0               0.0                              0.0
9                 0.0               0.0                              1.0
10                0.0               0.0                              1.0
11                0.0               0.0                              1.0
12                0.0               0.0                              1.0

In [127]:
dfhe_merged = pd.concat([df.drop(['Car Model'], axis=1), dfhe], axis=1)
dfhe_merged

    Mileage  Sell Price($)  ...  Car Model_BMW X5  Car Model_Mercedez Benz C class
0     69000          18000  ...               1.0                              0.0
1     35000          34000  ...               1.0                              0.0
2     57000          26100  ...               1.0                              0.0
3     22500          40000  ...               1.0                              0.0
4     46000          31500  ...               1.0                              0.0
5     59000          29400  ...               0.0                              0.0
6     52000          32000  ...               0.0                              0.0
7     72000          19300  ...               0.0                              0.0
8     91000          12000  ...               0.0                              0.0
9     67000          22000  ...               0.0                              1.0
10    83000          20000  ...               0.0                              1.0
11    79000          21000  ...               0.0                              1.0
12    59000          33000  ...               0.0                              1.0

[13 rows x 6 columns]

In [128]:
x = dfhe_merged.drop(['Sell Price($)', 'Car Model_Mercedez Benz C class'], axis=1)
x

    Mileage  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000         6                0.0               1.0
1     35000         3                0.0               1.0
2     57000         5                0.0               1.0
3     22500         2                0.0               1.0
4     46000         4                0.0               1.0
5     59000         5                1.0               0.0
6     52000         5                1.0               0.0
7     72000         6                1.0               0.0
8     91000         8                1.0               0.0
9     67000         6                0.0               0.0
10    83000         7                0.0               0.0
11    79000         7                0.0               0.0
12    59000         5                0.0               0.0

In [129]:
y = dfhe_merged['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [130]:
model = LinearRegression().fit(x, y)

In [131]:
model.predict([[45000,4,0,0]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36991.31721061])

In [132]:
model.predict([[86000, 7, 0, 1]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11080.74313219])

Alternate Method

In [133]:
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [134]:
dummy_cols = pd.get_dummies(df['Car Model'], dtype=int)
dummy_cols

    Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [135]:
df2 = df.copy()
df_merged = pd.concat([df2.drop(['Car Model'], axis=1), dummy_cols.drop(['Mercedez Benz C class'], axis=1)], axis='columns')
df_merged

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [136]:
x1 = df_merged.drop(['Sell Price($)'], axis=1)
x1

    Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6        0       1
1     35000         3        0       1
2     57000         5        0       1
3     22500         2        0       1
4     46000         4        0       1
5     59000         5        1       0
6     52000         5        1       0
7     72000         6        1       0
8     91000         8        1       0
9     67000         6        0       0
10    83000         7        0       0
11    79000         7        0       0
12    59000         5        0       0

In [137]:
y1 = df_merged['Sell Price($)']
y1

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [138]:
model2 = LinearRegression().fit(x1, y1)

In [139]:
model2.predict([[45000,4,0,0]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36991.31721061])

In [140]:
model2.predict([[86000, 7, 0, 1]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11080.74313219])