In [31]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [32]:
playtennis_df = pd.DataFrame({
    'Day': ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14'],
    'outlook': ['sunny', 'sunny', 'overcast', 'rain', 'rain', 'rain', 'overcast', 'sunny', 'sunny', 'rain', 'sunny', 'overcast', 'overcast', 'rain'],
    'temperature': ['hot', 'hot', 'hot', 'mild', 'cool', 'cool', 'cool', 'mild', 'cool', 'mild', 'mild', 'mild', 'hot', 'mild'],
    'humidity': ['high', 'high', 'high', 'high', 'normal', 'normal', 'normal', 'high', 'normal', 'normal', 'normal', 'high', 'normal', 'high'],
    'wind': ['weak', 'strong', 'weak', 'weak', 'weak', 'strong', 'strong', 'weak', 'weak', 'weak', 'strong', 'strong', 'weak', 'strong'],
    'playtennis': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']
})

playtennis_df

    Day   outlook temperature humidity    wind playtennis
0    D1     sunny         hot     high    weak         no
1    D2     sunny         hot     high  strong         no
2    D3  overcast         hot     high    weak        yes
3    D4      rain        mild     high    weak        yes
4    D5      rain        cool   normal    weak        yes
5    D6      rain        cool   normal  strong         no
6    D7  overcast        cool   normal  strong        yes
7    D8     sunny        mild     high    weak         no
8    D9     sunny        cool   normal    weak        yes
9   D10      rain        mild   normal    weak        yes
10  D11     sunny        mild   normal  strong        yes
11  D12  overcast        mild     high  strong        yes
12  D13  overcast         hot   normal    weak        yes
13  D14      rain        mild     high  strong         no

In [33]:
playtennis_df.drop(['Day'], axis=1, inplace=True)
playtennis_df

     outlook temperature humidity    wind playtennis
0      sunny         hot     high    weak         no
1      sunny         hot     high  strong         no
2   overcast         hot     high    weak        yes
3       rain        mild     high    weak        yes
4       rain        cool   normal    weak        yes
5       rain        cool   normal  strong         no
6   overcast        cool   normal  strong        yes
7      sunny        mild     high    weak         no
8      sunny        cool   normal    weak        yes
9       rain        mild   normal    weak        yes
10     sunny        mild   normal  strong        yes
11  overcast        mild     high  strong        yes
12  overcast         hot   normal    weak        yes
13      rain        mild     high  strong         no

In [34]:
le = LabelEncoder()

In [35]:
playtennis_df['outlook_n'] = le.fit_transform(playtennis_df.outlook)
playtennis_df['temperature_n'] = le.fit_transform(playtennis_df.temperature)
playtennis_df['humidity_n'] = le.fit_transform(playtennis_df.humidity)
playtennis_df['wind_n'] = le.fit_transform(playtennis_df.wind)

In [36]:
playtennis_df

     outlook temperature humidity  ... temperature_n humidity_n  wind_n
0      sunny         hot     high  ...             1          0       1
1      sunny         hot     high  ...             1          0       0
2   overcast         hot     high  ...             1          0       1
3       rain        mild     high  ...             2          0       1
4       rain        cool   normal  ...             0          1       1
5       rain        cool   normal  ...             0          1       0
6   overcast        cool   normal  ...             0          1       0
7      sunny        mild     high  ...             2          0       1
8      sunny        cool   normal  ...             0          1       1
9       rain        mild   normal  ...             2          1       1
10     sunny        mild   normal  ...             2          1       0
11  overcast        mild     high  ...             2          0       0
12  overcast         hot   normal  ...             1          1       1
13      rain        mild     high  ...             2          0       0

[14 rows x 9 columns]

In [37]:
playtennis_df.drop(['outlook', 'temperature',	'humidity',	'wind'], axis=1, inplace=True)

In [38]:
X = playtennis_df.drop('playtennis', axis=1)
Y = playtennis_df['playtennis']

In [39]:
X

    outlook_n  temperature_n  humidity_n  wind_n
0           2              1           0       1
1           2              1           0       0
2           0              1           0       1
3           1              2           0       1
4           1              0           1       1
5           1              0           1       0
6           0              0           1       0
7           2              2           0       1
8           2              0           1       1
9           1              2           1       1
10          2              2           1       0
11          0              2           0       0
12          0              1           1       1
13          1              2           0       0

In [40]:
Y

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: playtennis, dtype: object

In [41]:
model = DecisionTreeClassifier().fit(X, Y)

In [42]:
model.score(X, Y)

1.0

In [43]:
model.predict([[2, 1, 0, 1]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['no'], dtype=object)

In [44]:
model.predict([[2, 2, 1, 0]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['yes'], dtype=object)